### ISSUE TITLE
Missing files in unit tests

### ISSUE THREAD

**Issue by BBAerium** [maalik0786/FastYolo#1]
I am figuring out how this works, and noticed you have unit tests but have not included the weights, names, cfg's or dummy images.

Can you add those so I can get the unit tests going please?

**Comment by maalik0786** [comment]
download these files and use these files for unit tests: 
For configuration: https://github.com/pjreddie/darknet/blob/master/cfg/yolov2-tiny-voc.cfg
For Weights: https://pjreddie.com/media/files/yolov2-tiny-voc.weights
For names: https://github.com/AlexeyAB/darknet/blob/master/cfg/coco.data
For Image: take any image
