### ISSUE TITLE
C# Example please?

### ISSUE THREAD

**Issue by SecuritySlayer** [maalik0786/FastYolo#11]
Sorry i'm new to yolo i've been trying for a month for it to use gpu. How do i use this code. I's there like a code example? Like other yolo ver have?

**Comment by maalik0786** [comment]
Sorry for late reply, today we have released new version and there is help available [here](https://github.com/maalik0786/FastYolo/blob/master/README.md) how to use it
there are some tests available [here](https://github.com/maalik0786/FastYolo/blob/master/FastYolo.Tests/YoloWrapperTests.cs)

**Comment by maalik0786** [comment]
above reply should be enough
