### ISSUE TITLE
Unable to load DLL 'yolo_cpp_dll.dll' or one of its dependencies

### ISSUE THREAD

**Issue by KatterMaw** [maalik0786/FastYolo#14]
at FastYolo.YoloWrapper.GetDeviceCount()
   at FastYolo.YoloWrapper.Initialize(String configurationFilename, String weightsFilename, Int32 gpu)
   at FastYolo.YoloWrapper..ctor(String configurationFilename, String weightsFilename, String namesFilename, Int32 gpu)
   at Program.<Main>$(String[] args) in D:\Projects\FastYoloTest\FastYoloTest\Program.cs:line 10
   
Clean code, no code except
```
var image = Image.FromFile(ImageFilename);
using var memoryStream = new MemoryStream();
image.Save(memoryStream, image.RawFormat);
var byteArray = memoryStream.ToArray();

IEnumerable<YoloItem> yoloItems = yoloWrapper.Detect(byteArray);

foreach (var item in yoloItems)
    Console.WriteLine($"Object Found: {item.Type} with X: {item.X}, Y: {item.Y}, Width: {item.Width}, Height: {item.Height}");
```

CUDA 11.5 and cuDNN 8.3.2 installed.
There is the file in the folder:
![image](https://user-images.githubusercontent.com/68691636/156229496-99a66387-8635-4d1e-aa7c-396be361d372.png)

**Comment by KatterMaw** [comment]
The github usage guides specify the required version of Cuda 11.5, and the NuGet package description specifies the version of Cuda 11.6. After installing the version of Cuda 11.6, the previous problem seems to have been solved, but now another problem arises:
```
Could not load library cudnn_cnn_infer64_8.dll . Error code 126
Please make sure cudnn_cnn_infer64_8.dll is in your library path!
```
The latest version of cuDNN is currently installed.

**Comment by maalik0786** [comment]
https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-zlib-windows
Follow 3.1.3 and add zlibwapi.dll to your path or inside bin folder od cuda like 
![image](https://user-images.githubusercontent.com/54114655/156363758-bfe09472-735d-47de-a9f3-40edf8451909.png)

**Comment by maalik0786** [comment]
btw, Error code 126 is also mentioned in https://github.com/maalik0786/FastYolo/blob/master/README.md

**Comment by KatterMaw** [comment]
The error has been fixed, but now an error occurs when trying to detect:

```
System.NullReferenceException: Object reference not set to an instance of an object.
at Fast Yolo.Yolo Wrapper.Detect Image(Int Ptrarray, Int32 size, BboxContainer& container)
```

Moreover, such an exception appears when working from Rider, and when starting from VS2022, another exception appears:

`System.AccessViolationException: "Attempted to read or write protected memory. This is often an indication that other memory is corrupt."`

**Comment by maalik0786** [comment]
Did you try the code you mentioned in your first comment?

**Comment by maalik0786** [comment]
Please instead of byteArray just pass ImageFilename,i want to see its working or not

**Comment by KatterMaw** [comment]
No changes
![image](https://user-images.githubusercontent.com/68691636/156404663-59802a91-ca86-497d-bac7-dec0a8bbc7a0.png)

**Comment by maalik0786** [comment]
Fixed in 
<PackageReference Include="FastYolo" Version="11.6.2" />
