### ISSUE TITLE
CUDA Error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by arturitus** [maalik0786/FastYolo#20]
Hi.
I have installed the latest versions of CUDA and cuDNN.
Is my GPU not compatible, or did I do something wrong?
![image](https://user-images.githubusercontent.com/68915153/178118945-a0484792-c3f5-40af-8613-c7ed680d4681.png)
Help please!

**Comment by maalik0786** [comment]
Hi,
we are using CUDA 11 and GTX 960 is not supported
