### ISSUE TITLE
Working but on CPU

### ISSUE THREAD

**Issue by theo2f** [maalik0786/FastYolo#26]
Hi guys.
I want to use FastYolo to work with my custom model.
I followed the steps to create the project, added the nuget package and used the sample code.
The app is running without any errors, but it's running on CPU and not GPU.

Important to say that I can use GPU with other component on Yolov5, 7 and 8. My CUDNN configuration is fine.

I read see some tricks on readme doc to solve errors, but I could not find the solution for my problem.
I need any help. Thank you.

**Comment by uri-el99** [comment]
> Hi guys. I want to use FastYolo to work with my custom model. I followed the steps to create the project, added the nuget package and used the sample code. The app is running without any errors, but it's running on CPU and not GPU.
> 
> Important to say that I can use GPU with other component on Yolov5, 7 and 8. My CUDNN configuration is fine.
> 
> I read see some tricks on readme doc to solve errors, but I could not find the solution for my problem. I need any help. Thank you.

Hi guy, hope you are doing well.
I´m a begginer here so, I´d like to know if you could help how to use FastYolo if there´s no any problem with that.
Hope you can send some help, please.

**Comment by theo2f** [comment]
Check your CUDNN version and decrease/increase the FastYolo version accordingly to ensure compatibility.

For example, I use CUDNN 11.x:
![image](https://github.com/maalik0786/FastYolo/assets/5304192/08e0029d-2c0d-44b0-bef7-cfaedc4bc626)
