### ISSUE TITLE
Build errror. libopencv_world.so was not found

### ISSUE THREAD

**Issue by akaBronze** [maalik0786/FastYolo#4]
I try to build project and receive error message:
/home/akabronze/dotnet/sdk/5.0.201/Microsoft.Common.CurrentVersion.targets(4919,5): error MSB3030: Could not copy the file "/home/akabronze/FastYolo11/FastYolo/libopencv_world.so" because it was not found. 
[/home/akabronze/FastYolo11/FastYolo/FastYolo.csproj]
Where i can pick up libopencv_world.so
My machine: Jetson nano arm64. .net 5 installed

**Comment by maalik0786** [comment]
FastYolo new releases are compiled on CUDA 11 and CUDA 11 is not supported on Jetson nano. May be use old versions and get it working. if you have still issue paste the logs here with FastYolo version.

**Comment by maalik0786** [comment]
reopen the bug if not fixed
