### ISSUE TITLE
Nuget version missing DLLs

### ISSUE THREAD

**Issue by josuelopez-oceanscode** [maalik0786/FastYolo#5]
Hi,

Thanks for this amazing library. I wanted to report that nuget v11.1.1 is missing the required DLLs also in the master branch for this repo doesn't contain the required DLLs, I had to use nuget pckg v10 as these are included

**Comment by maalik0786** [comment]
Can you please tell the DLL's which are missing, we can add in the next release?
May be share your system details like OS, GPU, etc and share the logs.
