### ISSUE TITLE
FastYolo will not start

### ISSUE THREAD

**Issue by EinfachMaxYT** [maalik0786/FastYolo#6]
Hey there. 

FastYolo can't use the weight files from me:

![image](https://user-images.githubusercontent.com/72171280/133869888-853b45df-8f00-4c68-8119-125e3d985379.png)

What i can do?

System: GTX 1070
Cuda: 11.1.0

**Comment by EinfachMaxYT** [comment]
I fixed it (adding my compute in yolo_dll config. But now after it work i think it's not only GPU - It looks like CPU

**Comment by maalik0786** [comment]
In the next release we will support GTX, RTX, Jetson Xavier GPU's.
