### ISSUE TITLE
Failed to restore NuGet package

### ISSUE THREAD

**Issue by Yearang-Lee** [maalik0786/FastYolo#8]
Hi, thanks for sharing your code
When I build I get the following error:

Failed to restore NuGet package. For more information about warnings and errors, see the Error List window.
Elapsed time: 00:00:00.0300821
=========== Done ===========

Error restoring NuGet package local source 'C:\Users\FastYolo-master\FastYolo-master\References' does not exist.

If you know a solution, please let me know. 
Thank you.

**Comment by maalik0786** [comment]
You have to remove C++ project from the solution or clone the https://github.com/maalik0786/darknet.git and folder structure should be let say 'C:\Users is parent folder and clone both FastYolo and darkent in this directory. 
this should fix the nugut restore and also build the project successfully

**Comment by Yearang-Lee** [comment]
Hi,  thanks for the reply
 
I set the path well, but I'm not sure about this part.
"You have to remove C++ project from the solution"
 
I have built and used AlexeyAB/darknet, please tell me which files I need to remove within this folder.
 
Thanks again for your help.
 
-----Original Message-----
