### ISSUE TITLE
Leaks a lot of memory

### ISSUE THREAD

**Issue by StefanLundmark** [maalik0786/FastYolo#9]
FastYolo leaks a lot of memory. From the Windows Task Manager after 2 minutes of running every 100 ms:
![image](https://user-images.githubusercontent.com/2816866/136672311-476fd475-a34b-4387-8683-c169bf9ebe36.png)

This happens when calling Detect with a byte array. Commenting out that method call stops the leaks. Inside that method, Image is not disposed so that's one fix you can make. But even after that there's still some leaking, not sure where. Looking through the DLL's now.

**Comment by maalik0786** [comment]
this is fixed in the latest version 11.6.2
